inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'lib/coverage_links/**'

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/CommentAnnotation:
  Enabled: false

Style/StringConcatenation:
  Mode: conservative

