#!/usr/bin/env bash

# Safely try out a docker container with skiggety utils installed, to see what it's like
# without affecting your machine

. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash
SKIGGETY_DEBUG=true

# Work on this script with Kevin so he can be up and running to test todo:

# TODO: ./installers/docker || exit_with_error "Could not install Docker"
# XXX UNCOMMENT: ask_user "install docker"

cd $SKIGGETY_UTILS_DIR || exit_with_error "Could not find \$SKIGGETY_UTILS_DIR"

docker build -t skiggety-utils-box .
debug_here "docker build returned: $?"

docker run --rm -it --entrypoint bash skiggety-utils-box

# TODO: run a shell with a helpful intro message in the docker container

exit_with_error "TODO^15: "\
    "IMPLEMENT or vote by doing s/TODO/TODO TODO/" # IGNORE_TODO

# TODO: after you implement this, figure out what the shortes one liner is to checkout skiggety utils, and run this
# script.
