#!/usr/bin/env bash

# This script makes sure everything is installed, familiarizes you with what's here, and maybe even displays the dashboard

echo "starting at $(date) ..."

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
export SKIGGETY_UTILS_DIR="$THIS_DIR"
. $SKIGGETY_UTILS_DIR/lib/include_in_bashrc.bash || exit 1
. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash || exit 1

debug_here "utils successfully included"

debug_here "let's try running update-skiggety-utils:"
debug_here "--------------------------"
./bin/update-skiggety-utils || echo_error_here "Could not run \"./bin/update-skiggety-utils"

debug_here "update-skiggety-utils completed successfully"; echo

# TODO: I'm not even sure this is a good idea, but maybe reload ~/.bashrc and stuff now that it's been updated by ./install-skiggety-utils ? :       . ./lib/reload_env || exit_with_error "could not source \"./lib/reload_env\"" # TODO: don't use relative path
# debug_here
# TODO: this is something similar that I'm also not sure is a good idea: ./bin/start_in_env.bash || exit_with_error "Could not run \"./bin/start_in_env.bash\"" # TODO: don't use relative path # TODO^2: move most things in here, including any interactive stuff

shellask "let's take a look at the README.md, ok?" && less README.md || echo "...that's ok, we can skip the README.md"
# help_with_skiggety_utils # TODO^3: RENAME, test/implement something to show the help system if I do more with it.

debug_here "let's try running dev:"
debug_here "---------------------------"
shellask "let's run 'dev', ok?" && ./PWD_BIN/dev

echo
echo "You may want to run 'exec bash', to get a fresh shell now that you've set up some shell stuff"

echo
debug_here "dev completed successfully"
debug_here "exiting..."
exit 0

