#!/usr/bin/env bash

# This script makes sure everything is installed, familiarizes you with what's here, and maybe even displays the dashboard

echo "starting at $(date) ..."

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/lib/include_in_bashrc || exit 1
. $THIS_DIR/lib/skiggety-utils.bash || exit 1

debug_here "utils successfully included" # TODO TODO: use a flag to turn debug messages on or off

# TODO are "debug_here" and "echo_debug" redundant?

debug_here "let's try running install_me:"
debug_here "--------------------------"

./PWD_BIN/install_me || echo_error_here "Could not run \"./PWD_BIN/install_me"

debug_here "install_me completed successfully"; echo

# TODO: I'm not even sure this is a good idea, but maybe reload ~/.bashrc and stuff now that it's been updated by ./install_me ? :       . ./lib/reload_env || exit_with_error "could not source \"./lib/reload_env\"" # TODO: don't use relative path
# debug_here
# TODO: this is something similar that I'm also not sure is a good idea: ./bin/start_in_env.bash || exit_with_error "Could not run \"./bin/start_in_env.bash\"" # TODO: don't use relative path # TODO TODO: move most things in here, including any interactive stuff

# TODO TODO: make auto-dev optional, or maybe DELETE  calls to it, as that's not necessarily what this script is for..
debug_here "let's try running auto-dev:"
debug_here "---------------------------"
$THIS_DIR/bin/auto-dev || exit_with_error "FAILED to run auto-dev" #TODO: since this is in ./PWD_BIN/, I shouldn't need to use a relative path

echo
exit_with_error "Technically FAILED, but if you got here, that's good."
# exit_with_error "MOVABLE BREAKPOINT"
debug_here "auto-dev completed successfully"; echo
debug_here "exiting..."
help # TODO: test/implement
exit 0

