execute pathogen#infect()

set nocp
syntax enable

let mapleader = ","

set hlsearch
set incsearch                           " incremental searching

set textwidth=120
set colorcolumn=+1

"status bar
set laststatus=2 "Always show status bar
set ruler
set showcmd
set number
set relativenumber

highlight LineNr ctermfg=black ctermbg=grey

set autoindent
set wildmenu
set history=1000
set visualbell
filetype plugin indent on

" Auto-reload vimrc
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
" Run the current file with rspec
map <Leader>rb :Dispatch bin/rspec %<CR>

" fzf.vim:
" most of this fzf section is from https://dev.to/iggredible/how-to-search-faster-in-vim-with-fzf-vim-36ko :
set rtp+=/usr/local/opt/fzf "TODO: make this cross-platform, this is just where fzf gets installed with brew on mac
nnoremap <Leader>f :Rg<CR>
nnoremap <C-f> :Files<CR>
" TODO^15: learn/consider some of these:
" nnoremap <Leader>b :Buffers<CR> " TODO
" nnoremap <Leader>f :Rg<CR>
" nnoremap <Leader>/ :BLines<CR>
" nnoremap <Leader>' :Marks<CR>
" nnoremap <Leader>g :Commits<CR> " TODO
" nnoremap <Leader>H :Helptags<CR>
" nnoremap <Leader>hh :History<CR> " TODO
" nnoremap <Leader>h: :History:<CR> " TODO
" nnoremap <Leader>h/ :History/<CR> " TODO

" NERDCommenter
let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1

highlight KeywordForComments ctermbg=yellow guibg=yellow
au BufWinEnter * call matchadd("KeywordForComments", '\<\(TODO\|IGNORE_TODO\|XXX\|\(UN-\)\|HARDCODE\|DELETE\|UNCOMMENT\|COMMENT\|MAYBE\|ISSUE\|MOVE\|DEBUG\|REFACTOR\|EXPERIMENTAL\|byebug\)\>')

highlight TrailingWhiteSpace ctermbg=red guibg=red
au BufWinEnter * call matchadd("TrailingWhiteSpace", '\s\+$')

highlight LeadingTabs ctermbg=darkgreen guibg=darkgreen
au BufWinEnter * call matchadd("LeadingTabs", '\(^\s*\)\@<=\t')

set expandtab	"Don't actually put tab characters in files!!
set sw=4
set ts=8

autocmd Filetype sh set softtabstop=4
autocmd Filetype sh set sw=4

autocmd Filetype html set softtabstop=2
autocmd Filetype html set sw=2

autocmd Filetype ruby set softtabstop=2
autocmd Filetype ruby set sw=2

autocmd Filetype python set softtabstop=4
autocmd Filetype python set sw=4
autocmd Filetype python set textwidth=100
