#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class AhaInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    !!system('aha --version > /dev/null') # TODO: function extract tolibrary...just seeing if basic command works
  end

  def apparently_configured?
    true # nothing to configure, I think..
  end

  def install!
    if on_mac_os?
      # assert_system('brew tap masukomi/homebrew-apps') # TODO: function extract brew tap??
      brew_install_latest 'aha'
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

AhaInstaller.run
