#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class ArdourInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      false # raise NotImplementedError, 'TODO^37: implement this for this OS'
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

  def apparently_configured?
    true
  end

  def install!
    call_peer_installer('chrome')
    if on_mac_os?
      if $interactive
        delegate_download_and_install_to_user(
          'https://community.ardour.org/download?type=compiled',
          'Ardour'
        )
      else
        raise_interactive_only_install
      end
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

ArdourInstaller.run
