#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class ChromeInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    return true if in_docker_demo?

    if on_mac_os?
      # TODO: Checking the version would be a better approach if possible, I guess:
      Dir.exist?('/Applications/Google Chrome.app')
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

  def apparently_configured?
    return true if in_docker_demo?

    ask_user 'Are you signed in to Chrome, with your normal bookmarks and extensions?'
  end

  def install!
    if $interactive
      delegate_download_and_install_to_user('https://www.google.com/chrome/', 'Chrome')
    else
      raise_interactive_only_install
    end
  end

  def configure!
    delegate_to_user 'Sign in to Chrome'
  end

end

ChromeInstaller.run
