#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

# TODO^93 NOW: TEST this in docker as a reluctant user starting from fish

echo

if ! bc -v >/dev/null 2>&1; then
    if which apt-get >/dev/null && shellask "Want to install bc with apt-get?"; then
        apt-get -y update
        apt-get -y install bc
    fi
fi

if ! bc -v >/dev/null 2>&1; then
    exit_with_error "Please install bc and try again"
fi

if ! mplayer -v >/dev/null 2>&1; then
    if which brew >/dev/null && shellask "Want to install mplayer with brew?"; then
        brew install mplayer
    elif which apt-get >/dev/null && shellask "Want to install mplayer with apt-get (as root)?"; then
        sudo apt-get -y update
        sudo apt-get -y install mplayer
    fi
fi

if ! mplayer -v >/dev/null 2>&1; then
    exit_with_error "Please install mplayer and try again"
fi

echo "$0 SUCCEEDED"
exit 0
