#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class FzfInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    system 'which fzf'
  end

  def apparently_configured?
    true # no config
  end

  def install!
    call_peer_installer('ripgrep') # since fzf is configured to depend on ripgrep
    if on_mac_os?
      brew_install_latest 'fzf'
    elsif apt_available?
      if in_docker_demo?
        assert_system('apt install -y fzf')
      elsif $interactive
        assert_system('sudo apt install fzf')
      else
        raise_interactive_only_install
      end
    else
      raise 'TODO: IMPLEMENT'
    end
  end

end

FzfInstaller.run
