#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class FzfInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    system 'which fzf'
  end

  def apparently_configured?
    true # no config
  end

  def install
    if on_mac_os?
      brew_install_latest 'fzf'
    else
      raise 'TODO: IMPLEMENT'
    end
  end

end

FzfInstaller.run
