#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class GimpInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      return Dir.glob("/Applications/GIMP*.app").any?
    else
      return system("which gimp")
    end
  end

  def apparently_configured?
    return true # pretty sure there's nothing to do here
  end

  def install
    if on_mac_os?
      assert_system("brew install gimp")
    elsif has_apt?
      if $interactive
        assert_system("sudo apt install gimp")
      else
        raise_interactive_only_install
      end
    else
      raise NotImplementedError, "TODO: implement this for this OS" # If we install a different program similar to rectangle on a different OS, this script should be renamed.
    end
  end

end

GimpInstaller.run
