#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class GimpInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      Dir.glob('/Applications/GIMP*.app').any?
    else
      system('which gimp')
    end
  end

  def apparently_configured?
    true # pretty sure there's nothing to do here
  end

  def install
    if on_mac_os?
      brew_install_latest 'gimp'
    elsif apt_available?
      if $interactive
        assert_system('sudo apt install gimp')
      else
        raise_interactive_only_install
      end
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

GimpInstaller.run
