#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class HomebrewInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      return program_version_option_output_matches?('brew', / 2\./) # TODO: update desired version
    else
      return true
    end
  end

  def install
    if on_mac_os?
      if $interactive
        systemtrue?('brew update') or systemtrue?('/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"') or raise "failed to install homebrew, please check http://brew.sh"
      else
        raise_interactive_only_install
      end
    end
  end

  def apparently_configured?
    true
  end

end

HomebrewInstaller.run
