#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class HomebrewInstaller

  include InstallableSkiggetyUtil

  def self.run # TODO: extract to InstallableSkiggetyUtil
    self.new.run
  end

  def apparently_installed?
    if on_mac_os?
      homebrew_version = `brew --version `
      return (homebrew_version =~ / 2\.4/ ).is_a?(Numeric) # TODO: update desired version and make sure it includes the gui version, too
    else
      return true
    end
  end

  def install
    if on_mac_os?
      if $interactive
        system('/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"')
        raise "failed to install homebrew, please check http://brew.sh" unless ($? == 0 )
      else
        raise_install_non_interactive
      end
    end
  end

  def apparently_configured?
    true
  end

end

HomebrewInstaller.run
