#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class HostnameChooser

  include InstallableSkiggetyUtil

  raise "TODO TODO TODO: IMPLEMENT"
  # TODO: perhaps require installers/hostname.config/localhost.gitignore.txt
  # TODO: perhaps require dns server config (check with nslookup or an equivalent library)

end

HostnameChooser.run
