#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class HostnameSetup

  # TODO TODO: perhaps require "installers/hostname.config/localhost.gitignore.txt", but maybe the user shouldn't have to create it manually
  # enforce all-lowercase, numbers not in first character, etc. ...or whatever works for dns
  # TODO: perhaps require dns server config (check with nslookup or an equivalent library) --this might help with synergy config, etc.
    # TODO: To systematize this you could find the ip address of the local gatteway and pop it up in a browser

  include InstallableSkiggetyUtil

  def apparently_installed?
    true # nothing to install
  end

  def apparently_configured?
    desired_hostname == `hostname`
  end

  def configure
    if on_mac_os?
      if $interactive
        puts "Sudo password will be needed to set hostname:"
        %w(LocalHostName ComputerName).each do |sc_name|
          assert_system("sudo scutil --set #{sc_name} #{desired_hostname}")
        end
      else
        raise_interactive_only_configuration
      end
    else
      raise NotImplementedError, "TODO: implement this for this OS"
    end
  end

  def desired_hostname
    @desired_hostname ||= calc_desired_hostname
  end

  def calc_desired_hostname
    desired_hostname_file = self_config_path('localhost.gitignore.txt')
    if File.exist?(desired_hostname_file)
      `cat #{desired_hostname_file}`
    else
      raise "Please put desired hostname in #{desired_hostname_file} and try again"
    end
  end

end

if __FILE__ == $0 # TODO: use this more widely if call_peer_installer uses a direct include method?
  puts "Running \"#{$0}\"!" # TODO: DELETE
  HostnameSetup.run
else
  puts "Including \"#{$0}\"!" # TODO: DELETE
end
