#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class JigglerInstaller

  include InstallableSkiggetyUtil

  raise 'TODO^2: IMPLEMENT'

end

JigglerInstaller.run
