#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class LocalBackupSetterUpper

  include InstallableSkiggetyUtil

  def self.run # TODO: extract to InstallableSkiggetyUtil
    self.new.run
  end

end

LocalBackupSetterUpper.run
