#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class PstreeInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    system 'which pstree'
  end

  def apparently_configured?
    true # no config
  end

  def install
    if on_mac_os?
      brew_install_latest 'pstree'
    elsif apt_available?
      if in_docker_demo?
        assert_system('apt install -y psmisc')
      elsif $interactive
        assert_system('sudo apt install psmisc')
      else
        raise_interactive_only_install
      end
    else
      raise 'TODO: IMPLEMENT'
    end
  end

end

PstreeInstaller.run
