#!/usr/bin/env ruby

# NOTE: using https://github.com/rxhanson/Rectangle because Spectacle is going to be unmaintained: https://github.com/eczarny/spectacle#important-note

require_relative '../lib/installable_skiggety_util.rb'

class RectangleInstaller

  include InstallableSkiggetyUtil

  def self.run # TODO: extract to InstallableSkiggetyUtil
    self.new.run
  end

  def apparently_installed?
    if on_mac_os?
      return File.exist?("/Applications/Rectangle.app")
    else
      return true
    end
  end

  def apparently_configured?
    return false # TODO: DELETE
    raise "TODO"
  end

  def install
    if on_mac_os?
      # Using homebrew for the install, which means I need to install homebrew as a dependency, only if on a mac though.

      # TODO: method extract call_peer_installer:
      homebrew_install_command = File.join(File.dirname(__FILE__),"homebrew")
      unless $interactive
        homebrew_install_command = homebrew_install_command + " --non-interactive"
      end
      system(homebrew_install_command)
      raise "Cannot install rectangle, because homebrew install failed" unless ($? == 0 )

      system("brew cask install rectangle")
      raise "rectangle install failed" unless ($? == 0 )
    end
  end

  def configure
    if on_mac_os?
      if $interactive
        system("open /Applications/Rectangle.app")
        system("#{__dir__}/../bin/ask_user_to 'set up Rectangle'")
        unless ( $?.exitstatus == 0 )
          raise "user failed to configure #{name}"
        end
      else
        raise "Cannot configure rectangle in non-interactive mode, user should run \"install_me\" or \"#{__FILE__}\"."
      end
    end
  end

end

RectangleInstaller.run
