#!/usr/bin/env ruby

# NOTE: using https://github.com/rxhanson/Rectangle because Spectacle is going to be unmaintained: https://github.com/eczarny/spectacle#important-note

require_relative '../lib/installable_skiggety_util.rb'

class RectangleInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      return Dir.exist?("/Applications/Rectangle.app")
    else
      return true # rectangle not available for other OS'es, I think # TODO: but maybe install some equivalent
    end
  end

  def apparently_configured?
    # TODO TODO: method/module extract?
    if $interactive
      ask_user "Is #{name} set up the way you want?"
    else
      # In non-interactive mode, assume config is needed to make sure the user
      # has a chance, since I can't think of a way to check if the current
      # config is the desired version:
      return false
    end
  end

  def install
    if on_mac_os?
      assert_system("brew cask install rectangle")
    else
      raise NotImplementedError, "TODO: implement this for this OS"
    end
  end

  def configure
    if on_mac_os?
      if $interactive
        assert_system("open /Applications/Rectangle.app")
        delegate_to_user "Configure #{name}"
      else
        raise_interactive_only_configuration
      end
    end
  end

end

RectangleInstaller.run
