#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class ReviewInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    false # just play it safe and make sure # TODO: fix this?
  end

  def apparently_configured?
    true # no config needed for now
  end

  def install!
    call_peer_installer('basic_prerequisites')
    system 'skiggety_env_exec ruby_setup' or raise "'ruby_setup' failed"
    mark_installed! # TODO: DELETE once we implement apparently_installed? for real
  end

end

ReviewInstaller.run
