#!/usr/bin/env ruby
# frozen_string_literal: true

# ripgrep is AKA rg, a way faster recursive grep

require_relative '../lib/installable_skiggety_util'

class RipgrepInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    program_version_option_output_matches?('rg', / 13\.0\.0 /)
  end

  def apparently_configured?
    true # no config
  end

  def install
    if on_mac_os?
      brew_install_latest 'rg'
    else
      raise 'TODO: IMPLEMENT'
    end
  end

end

RipgrepInstaller.run
