#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class SynergyInstaller

  include InstallableSkiggetyUtil

  raise "TODO TODO TODO TODO: IMPLEMENT"

end

SynergyInstaller.run
