#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class TerminalProfileConfigurer

  include InstallableSkiggetyUtil

  def apparently_installed?
    true # this is configuration only
  end

  def apparently_configured?
    if on_mac_os?
      return false # just assume it's needed if the marker file isn't there
    elsif on_linux_os?
      if ( ! File.exist?(user_qterminal_ini_path) )
        return false
      end
      FileUtils.compare_file(user_qterminal_ini_path, template_qterminal_ini_path)
    else
      return false # TODO: IMPLEMENT
      # TODO: commit/sync/install linux terminal profiles?
    end
  end

  def configure
    if $interactive
      if on_mac_os?
        # TODO: deal with the extra clutter of profiles like "skiggterm 1", "skiggterm 2", etc. that pile up sometimes. I'm not sure how much of a problem this is going to be in practice
        assert_system("open #{skiggterm_mac_profile_path}")
        delegate_to_user 'confirm that a terminal window just opened and has skiggterm in the title (you may close that window)'
        assert_system('defaults write com.apple.Terminal "Default Window Settings" skiggterm')
        assert_system('defaults read com.apple.Terminal "Default Window Settings"') # this is an attempt to get this setting to stick after the terminal restarts
        delegate_to_user 'Make sure skiggterm is the default, especially when the terminal is restarted --you can quit this installer by running exit 1 and restart if you need to'
      elsif on_linux_os?
        assert_system("vim -d #{user_qterminal_ini_path} #{template_qterminal_ini_path}")
      else
        raise NotImplementedError, "TODO: implement this for this OS"
      end
    else
      raise_interactive_only_configuration
    end
  end

  def user_qterminal_ini_path
    @user_qterminal_ini_path ||= File.expand_path('~/.config/qterminal.org/qterminal.ini')
  end

  def template_qterminal_ini_path
    self_config_path('qterminal.ini')
  end

  def skiggterm_mac_profile_path
    @skiggterm_mac_profile_path ||= self_config_path('skiggterm.terminal')
  end

end

TerminalProfileConfigurer.run

