#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

raise 'TODO TODO TODO TODO TODO: IMPLEMENT'

# TODO: handle tmux config like vim config, by bringing up a diff window between ~/.tmux.conf and
# ./installers/tmux.config/tmux.conf
