#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class UltimateHackingKeyboardAgentInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    return true if in_docker_demo?

    if on_mac_os?
      Dir.exist?('/Applications/UHK Agent.app')
    elsif on_linux_os?
      false
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

  def apparently_configured?
    return true if in_docker_demo?

    # TODO: ask user less stuff, but we still need a way to return true here when it's been done:
    ask_user 'Has the UHK has been set up OK?'
  end

  def install!
    delegate_download_and_install_to_user('https://ultimatehackingkeyboard.com/start/agent', 'UHK Agent')
  end

  def configure!
    if on_mac_os?
      if $interactive
        assert_system("open '/Applications/UHK Agent.app'")
        delegate_to_user "Configure #{name}"
      else
        raise_interactive_only_configuration
      end
    elsif on_linux_os?
      if $interactive
        delegate_to_user "Configure #{name}"
      else
        raise_interactive_only_configuration
      end
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

UltimateHackingKeyboardAgentInstaller.run
