#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class UltimateHackingKeyboardAgentInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      return Dir.exist?("/Applications/UHK Agent.app")
    else
      raise NotImplementedError, "TODO: implement this for this OS"
    end
  end

  def apparently_configured?
    false # assume we need configuration done if the marker file isn't there
  end

  def install
    download_url = "https://ultimatehackingkeyboard.com/start/agent"
    if $interactive
      open_in_browser(download_url)
      delegate_to_user('Download/install UHK Agent manually. The download page should be open now.')
    else
      raise_interactive_only_install
    end
  end

  def configure
    if on_mac_os?
      if $interactive
        assert_system("open '/Applications/UHK Agent.app'")
        delegate_to_user "Configure #{name}"
      else
        raise_interactive_only_configuration
      end
    else
      raise NotImplementedError, "TODO: implement this for this OS"
    end
  end


end

UltimateHackingKeyboardAgentInstaller.run

