#!/usr/bin/env ruby

require_relative '../lib/installable_skiggety_util.rb'

class VimInstaller

  include InstallableSkiggetyUtil

  def self.run # TODO: extract to InstallableSkiggetyUtil
    self.new.run
  end

  def apparently_installed?
    vim_version = `vim --version | head -n 1`
    return (vim_version =~ /8\.0/ ).is_a?(Numeric) # TODO: update desired vim version and make sure it includes the gui version, too
  end

  # err on the side of returning false...if these files don't match perfectly the user will have a chance to make sure it's set up right.
  def apparently_configured?
    FileUtils.compare_file(user_vimrc_path, template_vimrc_path)
  end

  def install
    if $interactive
      system("#{__dir__}/../bin/ask_user_to 'make sure vim is installed'")
      unless ( $?.exitstatus == 0 )
        raise "user failed to install vim"
      end
    else
      raise "skipping interactive vim install/config"
    end
  end

  def configure
    if $interactive
      system("vim -do #{user_vimrc_path} #{__FILE__}.config/vimrc") # TODO: extract path to config dir to InstallableSkiggetyUtil
    else
      raise "skipping interactive vim install/config"
    end
  end

  def user_vimrc_path
    File.expand_path('~/.vimrc')
  end

  def template_vimrc_path
    File.join(config_dir_path,'vimrc')
  end

end

VimInstaller.run
