#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

# TODO TODO TODO: install and set up vimpager as your pager, but maybe not in this installer
# TODO TODO: install vim rake plugin with vim pathogen
# TODO: maybe detect local vimrc changes

class VimInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    program_version_option_output_matches?('vim', / 8\.0 /)
  end

  # err on the side of returning false...if these files don't match perfectly
  # the user will have a chance to make sure it's set up right.
  def apparently_configured?
    return false unless File.exist?(user_vimrc_path)

    FileUtils.compare_file(user_vimrc_path, template_vimrc_path)
  end

  def install
    if $interactive
      delegate_to_user 'make sure vim is installed'
    else
      raise_interactive_only_install
    end

    if on_mac_os?
      brew_install_latest 'macvim'
      # TODO TODO: install gvim (gui) for linux
    end
  end

  def configure
    if $interactive
      assert_system("vim -do #{user_vimrc_path} #{template_vimrc_path}")
    else
      raise_interactive_only_configuration
    end
  end

  def user_vimrc_path
    @user_vimrc_path ||= File.expand_path('~/.vimrc')
  end

  def template_vimrc_path
    self_config_path('vimrc')
  end

end

VimInstaller.run
