#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class VisualStudioCodeInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      Dir.exist?('/Applications/Visual Studio Code.app')
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

  def apparently_configured?
    false
  end

  def configure!
    system("open 'https://code.visualstudio.com/docs/setup/mac'")
    delegate_to_user 'configure the path with VS code as it says at https://code.visualstudio.com/docs/setup/mac'
    mark_configured!
  end

  def install!
    if on_mac_os?
      brew_install_cask_latest 'visual-studio-code'
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

VisualStudioCodeInstaller.run
