#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

class VisualStudioCodeInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    if on_mac_os?
      Dir.exist?('/Applications/Visual Studio Code.app')
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

  def apparently_configured?
    true
  end

  def install!
    if on_mac_os?
      brew_install_cask_latest 'visual-studio-code'
    else
      raise NotImplementedError, 'TODO: implement this for this OS'
    end
  end

end

VisualStudioCodeInstaller.run
