#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

cd $SKIGGETY_UTILS_DIR || exit_with_error "could not cd to $SKIGGETY_UTILS_DIR"

# TODO^191: (TESTING IN_PROGRESS, NOW) this call to that other script thingy:
if ! git rev-parse; then
    vital-put-vital-dir-in-a-repository || exit 1
fi
