#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

# TODO^113: and devote some thought to dependencies between firstlife and skiggety-utils
# - TODO^116: make this, and maybe all installers, optional.  We could use marker files to keep track of preferences

class ZerothLifeInstaller

  include InstallableSkiggetyUtil

  def code_dir
    # Assume that where skiggety utils is parked is where you want to check out code:
    File.dirname(ENV.fetch('SKIGGETY_UTILS_DIR', nil))
  end

  def install_dir
    "#{code_dir}/zerothlife"
  end

  def apparently_installed?
    Dir.exist?(install_dir)
  end

  def install!
    git_clone_latest('https://github.com/skiggety/zerothlife', install_dir)
    git_safe_pull(install_dir)
  end

  def apparently_configured?
    false # TODO: check for bash include script
  end

  def configure!
    git_pull(install_dir)

    # TODO^127: (IN_PROGRESS, NOW) add the new repo's bin dir to your path by copying and allowing the user to modify, a
    # bash include script. skiggety-utils should include it if it exists, and firstlife/zerothlife, should
    # firslife-delegate you to do it

    # TODO^114: after install is implemented, call 'firstlife-setup'
  end

end

ZerothLifeInstaller.run
