#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/installable_skiggety_util'

# TODO^116: (IN_PROGRESS, NOW) at least check out the zerothlife repo, maybe with a skiggety-utils installer
# TODO^115: and add it's bin dir to your path
# TODO^114: and then call 'firstlife-setup'
# TODO^113: and devote some thought to dependencies between firstlife and skiggety-utils

class ZerothLifeInstaller

  include InstallableSkiggetyUtil

  def apparently_installed?
    raise 'TODO: IMPLEMENT'
  end

  # TODO: Only if you have access: TODO: how about some way to get updates, other than relying on firstlife itself? When
  # should this script do a git-safe-pull?

  def install!
    git_clone_latest('https://github.com/skiggety/zerothlife', "#{code_dir}/zerothlife")
  end

end

ZerothLifeInstaller.run
