#!/usr/bin/env bash

# This script ... (TODO)
# TODO: possible script renaming--ci means continuos. This is just the integration part. "auto-ci" could become "ci" and this would become what? "i"? I dunno. Something to think about.

# TODO: maybe extract "dev" out of auto-dev like this was extracted out of auto-dev

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/include_in_bashrc || exit 1
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

clear

# TODO: deal with any local changes...delete them?

echo_divider_with_text "-" "git pull:"
git pull # TODO checkout fresh code, default to one branch

echo_divider_with_text "-" "test_all:"
test_all && echo "test_all SUCCEEDED" || accumulate_error "test_all FAILED"
dashboard
