#!/usr/bin/env bash

# This script ... (TODO TODO)
# TODO TODO: possible script renaming--ci means continuos. This is just the integration part. "auto-ci" could become "ci" and this would become what? "i"? I dunno. Something to think about.

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/include_in_bashrc.bash || exit 1
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

# TODO: deal with any local changes...delete them? ...error out?

echo_divider_with_text "-" "git pull:"
git pull # TODO checkout fresh code, default to one branch

test_all && echo "test_all SUCCEEDED" || accumulate_error "test_all FAILED"

dashboard || accumulate_error "dashboard FAILED"

exit_with_any_accumulated_errors
