#!/usr/bin/env bash

# This script prints a summary of the status of development (or whatever) in the current directory, including
# information about git, todo's, tests, etc.  It can often simply call default_dashboard from the path.

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash || exit 1

echo_divider_with_text "O-=======-" "'dashboard' for $(duh) :"

function complain_about_keyword_usage {
    rg_glob_args=''
    while [[ "$1" == -* ]]; do
        if [ "$1" == "-g" ]; then
            shift
            rg_glob_args="-g $1"
            shift
        fi
    done
    keyword="$1"
    suggested="$2"

    rg -n $keyword $rg_glob_args --color=always | sort | abbreviate --auto -t "-------- change these mentions of '$keyword' to '$suggested': --------"
}

complain_about_keyword_usage today_todo vital # EASY TODO^44: clean up legacy today_todo usage

# show unstaged stuff:
unstaged_todos="$(git diff | grep '^+.*TODO' | grep -v 'IGNORE_TODO')"
debug_here
unstaged_files="$(git status -s | grep '^?')"
debug_eval_here unstaged_files
debug_here
if [ -n "$unstaged_files" ]; then
    debug_here
    unstaged_todos="$(rg TODO $(echo "$unstaged_files" | awk '{print $2}') | grep -v "IGNORE_TODO" | sort)$unstaged_todos" # get the ones in unstaged files too
    debug_here
fi
debug_eval_here unstaged_todos
unstaged_todos_count="$(echo "$unstaged_todos" | wc -l)"
unstaged_todos_count="$(( $unstaged_todos_count ))"
if [ -z "$unstaged_todos" ]; then
    unstaged_todos_count=0
fi
unstaged_todos="$(echo "$unstaged_todos" | abbreviate --auto-scale )" # AFTER getting the linecount
if [ $unstaged_todos_count -gt 0 ]; then
    echo_divider_with_text "=" "${RED}$unstaged_todos_count unstaged TODO's:${no_color}" # IGNORE_TODO
    echo "$unstaged_todos"
fi

bin/default_dashboard || accumulate_error "default_dashboard FAILED"
# Anything after this point better be more important than the output of default_dashboard since it could bump it off the
# screen....:

$SKIGGETY_UTILS_DIR/PWD_BIN/todo-report || accumulate_error 'todo-report errored'

complain_about_keyword_usage -g '!installers/zerothlife*' 'zl''-' ' ...another location... '  || accumulate_error "You might be depending on zerothlife by accident"

# TODO^5: maybe also make sure that lines that contain (all capitalized, not shown here so as not to tag this todo) 'todo' and 'now' also contain 'in_progress

echo_divider_with_text "O-=======-" "END of 'dashboard' for $(duh) :"

exit_with_any_accumulated_errors
