#!/usr/bin/env bash

# This script performs one development cycle, whatever that means in any individual project. For this project, it means
# running unit-test and showing the dashboard.

# TODO: in bin/, should there be a dev and a default-dev like with dashboard?

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/include_in_bashrc.bash || exit 1
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

echo_divider_with_text "#" "running 'dev':"

unit-test && echo "unit-test SUCCEEDED" || exit_with_error "unit-test FAILED"

lint && echo "lint SUCCEEDED" || exit_with_error "lint FAILED"

dashboard || accumulate_error "dashboard FAILED"

# TODO: ask Kevin to test if this generation is working for him and if it shows up in his 'todo' output:
experiment_script="./PWD_BIN/experiment.gitignored.bash"
if ! [ -f "$experiment_script" ]; then
    echo "#!$(which env) bash" > "$experiment_script"
    echo >> "$experiment_script"
    echo ". \$SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash || exit 1" >> "$experiment_script"
    echo "SKIGGETY_DEBUG=true" >> "$experiment_script"
    echo >> "$experiment_script"
    echo "# TODO: edit this, and it will be run/shown by '$(basename $0)'." >> "$experiment_script" # IGNORE_TODO
    chmod +x "$experiment_script"
fi

if [ -f "$experiment_script" ]; then
    echo_divider_with_text "=" "running \"$experiment_script\" :"
    $experiment_script || accumulate_error "experimental script \"$experiment_script\" FAILED"
fi

echo_divider_with_text "#" "END of 'dev'."
exit_with_any_accumulated_errors
