#!/usr/bin/env bash

# This script performs one development cycle, whatever that means in any individual project. For this project, it means running test_all and showing the dashboard.

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/include_in_bashrc.bash || exit 1
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

echo_divider_with_text "//======" "dev:"

test_all && echo "test_all SUCCEEDED" || accumulate_error "test_all FAILED"

exit_if_any_accumulated_errors

dashboard || accumulate_error "dashboard FAILED"

exit_if_any_accumulated_errors
