#!/usr/bin/env bash

TODO_REPORT_LINES=5 # IGNORE_TODO
TODO_REPORT_DIR="todo_report" # IGNORE_TODO
TODO_REPORT_FILE="$TODO_REPORT_DIR/README.txt" # IGNORE_TODO
TODO_REPORT_COLOR_FILE="$TODO_REPORT_DIR/README_in_color.txt" # IGNORE_TODO

. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash

debug_eval_here TODO_REPORT_FILE # IGNORE_TODO
debug_eval_here TODO_REPORT_COLOR_FILE # IGNORE_TODO
mkdir -p "$TODO_REPORT_DIR" # IGNORE_TODO

todo_report_whole="$(todo --exclude-dir "$TODO_REPORT_DIR" | grep -v ".gitignored." | grep -v "XXX")"
todo_report_body="$(echo "$todo_report_whole" | tail -n $TODO_REPORT_LINES )"
todo_report_color_body="$(echo "$todo_report_body" |  grep --color=always TODO )"
todo_report_linecount=$(echo "$todo_report_whole" | wc -l | sed 's/^[ \t]*//')
todo_header="Here are the most important $TODO_REPORT_LINES todos, most important last, out of ${todo_report_linecount##*()} total."

echo "$todo_header" > $TODO_REPORT_FILE
echo "$todo_header" > $TODO_REPORT_COLOR_FILE
SKIGGETY_DIVIDER_LENGTH=80 echo_divider "=" >> $TODO_REPORT_FILE
SKIGGETY_DIVIDER_LENGTH=80 echo_divider "=" >> $TODO_REPORT_COLOR_FILE
echo "$todo_report_body" >> $TODO_REPORT_FILE
echo "$todo_report_color_body" >> $TODO_REPORT_COLOR_FILE

cat $TODO_REPORT_COLOR_FILE
