#!/usr/bin/env bash

TODO_REPORT_LINES=5 # IGNORE_TODO
TODO_REPORT_FILE="todo_report/README.txt"

. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash

SKIGGETY_DEBUG=true # XXX

debug_eval_here TODO_REPORT_FILE
debug_here mkdir -p "$(dirname "$TODO_REPORT_FILE")"
mkdir -p "$(dirname "$TODO_REPORT_FILE")"

# TODO^17: in the future, use 'todo --exclude <FILE>' (when it's supported) instead of relying on 'grep -v'
todo_report="$(todo | grep -v "^./${TODO_REPORT_FILE}:" | grep -v ".gitignored." | grep -v "XXX" | tail -n $TODO_REPORT_LINES )"
echo "Here are the most important $TODO_REPORT_LINES todos, most important last, out of TODO total." > $TODO_REPORT_FILE
echo "$todo_report" >> $TODO_REPORT_FILE

cat $TODO_REPORT_FILE
