#!/usr/bin/env bash

# This script takes into account that some files are generated and you don't care about local changes to make git pull
# easier.

. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash || exit 1

git restore todo_report
git-pretty-pull || exit_with_error "git-pretty-pull FALED"

# TODO^2: ???: git restore --staged .
