#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

# TODO TODO TODO: Rewrite this in ruby or python...we need to do some smart

# TODO TODO: things to handle inter-installer dependencies, retrying only
# TODO TODO: as many times as will be helpful, etc. For now, I'll do a
# TODO TODO: dummy version that will speed through a few of them.
    # TODO: when an installer succeeds, hash the file contents, and save out a file (ignored_by_git) with the hash in it's name. That means that version of the file need not be run again.

# TODO: install-skigg-utils || exit_with_error "TODO"
# TODO: setup-computer || exit_with_error "TODO"
    # TODO: including bashrc, bash prompt, etc.
    # TODO TODO: make sure path to skigg_utils bin is in your .bashrc
    # TODO: reload bashrc
# TODO: install and configure 3rd party programs
    # TODO: install pocket

# TODO TODO: RECOVER/INSTALL: .bashrc
# TODO TODO TODO: install rectangle

function main {
    for arg in "$@"
    do
        shift
        case "$arg" in
            --non-interactive) set -- "$@" "-n" ;;
            *)                 set -- "$@" "$arg" ;;
        esac
    done

    # defaults
    interactive=true

    OPTIND=1
    while getopts ":inhi?" opt
    do
        case "$opt" in
            "i") interactive=true ;;
            "n") interactive=false ;;
            "h") exit_with_error "TODO: print usage" ;;
            "?") exit_with_error "TODO: print usage" ;;
            *) ;;
        esac
    done

    # TODO: get latest code (git pull)?

    local INSTALLER_ARGS=""
    if $interactive
    then
        INSTALLER_ARGS=""
    else
        INSTALLER_ARGS="--non-interactive"
    fi

    INSTALLERS_DIR="$THIS_DIR/../installers"

    for installer in "$INSTALLERS_DIR"/* # TODO: files only
    do
        if [ -f "$installer" ]; then

            # TODO: instead of exiting on error, note it and move on. $cumulative_exit_code might be handy
            use_installer "$installer" $INSTALLER_ARGS || accumulate_error "use_installer \"$installer\" FAILED ($(echo_here))"

            # configure "installer.config/" || exit_with_error "TODO" #  TODO: shoulcn't this be part of the installer?
            # TODO: make sure apps get configured properly, too, such as synergy, vim (incl vimrc), etc.
        fi
    done

    exit_with_any_accumulated_errors
}

# this function runs the installer, checks the exit code, prints context/formatting around it, perhaps remembers if it has already succeeded.
function use_installer {
    local installer_path="$1"
    local INSTALLER_ARGS="$2"
    installer="$(basename $installer_path)"

    # TODO: DELETE this temporary special-case crap as soon as I can, probably when this gets rewritten in a real language:
    if [[ "$installer" == "gimp" ||
          "$installer" == "jiggler" ||
          "$installer" == "rvm" ||
          "$installer" == "ssh-agent" ||
          "$installer" == "synergy" ||
          "$installer" == "uhk" ]]; then
        # TODO?: debug_here "skipping \"$installer\" installer for now..."
        return 0
    else
        $installer_path $INSTALLER_ARGS || { echo_error_here "installer \"$installer\" FAILED"; return 1; }
        # TODO TODO TODO TODO: if installer fails, count it as a failure in a variable "$cumulative_exit_status" and exit on error later, with a suggestion to re-run "install" manually
    fi
}

main "$@"
