#!/usr/bin/env bash

# TODO^6: make this read-only by default, split the write version into another script if necessary
# TODO^4: run shellcheck

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

echo_divider_with_text "O-=======-" "lint:"

echo_divider_with_text "+-=======-" "collapse todo votes:"
todo -wfq --non-interactive --exclude-dir .git || accumulate_error "could not write simplified TODO entries, todo exited with $?" # IGNORE_TODO

echo_divider_with_text "+-=======-" "generate ./todo_report/README.txt:"
generate_todo_report >/dev/null || accumulate_error 'could not generate todo report'
echo "The most important todo is currently:"
tail -n 1 todo_report/README.txt

echo_divider_with_text "+-=======-" "pylint:"
# TODO: abbreviate output?:
# TODO^4 automatically scan all python files:
# TODO^5: get in the habit of keeping everything clean and then use accumulate_error here:
pylint --rcfile .pylintrc bin/todo_5 lib/todo_line.py bin/demo_python_version_hack || warn_here 'TEMPORARILY IGNORING the fact that pylint reported ERRORS'

echo_divider_with_text "+-=======-" "rubocop:"
# TODO: call rupocop with -a OR -P depending on whether this script is in write mode or not (this script should have
# that as a distinct mode like todo does)
bundle exec rubocop -P --color || accumulate_error 'rubocop reported errors'

exit_with_any_accumulated_errors
