#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

echo_divider_with_text "O-=======-" "lint:"

echo_divider_with_text "+-=======-" "collapse todo votes:"
todo -wfq --non-interactive --exclude-dir .git || accumulate_error "could not write simplified TODO entries, todo exited with $?" # IGNORE_TODO

echo_divider_with_text "+-=======-" "generate ./todo_report.gen.txt:"
generate_todo_report >/dev/null || accumulate_error 'could not generate todo report'
echo "The most important todo is currently:"
tail -n 1 todo_report.gen.txt

echo_divider_with_text "+-=======-" "rubocop:"
bundle exec rubocop -P --color || accumulate_error 'rubocop reported errors'

echo_divider_with_text "+-=======-" "pylint:"
# TODO: abbreviate output?:
pylint --rcfile .pylintrc bin/todo lib/todo_line.py || accumulate_error 'pylint reported errors' # TODO automatically scan all python files

exit_if_any_accumulated_errors
