#!/usr/bin/env bash

# This script continuously checks out fresh code and tries it out

# TODO^2: after the RENAME/redesign of 'ci', this script probably will get DELETEd

# TODO: consider splitting to default_ and normal version like dashboard and lint
review -u 600 -m 1800 -M $(( 24 * 60 * 60)) ci # EASY TODO^37: review --ignore-disk (pass a flag for 'review' to ignore filesystem changes, since it is affected by git pull), necessary for this script to be genuinely useful
