#!/usr/bin/env bash

# This script continuously checks out fresh code and tries it out

# TODO^2: after the RENAME/redesign of 'ci', this script probably will get DELETEd

# TODO: consider splitting to default_ and normal version like dashboard and lint
review -m 60 -M 7200 ci
