#!/usr/bin/env bash

# This script runs tests this project as much as possible, and exits with an error if it fails.

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

echo_divider_with_text "O-=======-" "test_all:"

build

# install skiggety-utils
echo_divider_with_text "+-=======-" "install-skiggety-utils --non-interactive"
$THIS_DIR/install-skiggety-utils --non-interactive || exit_with_error "could not run installers for skiggety-utils"

echo_divider_with_text "+-=======-" "ruby_setup"
{ $THIS_DIR/ruby_setup 2>&1 || echo FOO; } | tail -n 1 # in case this part gets skipped in installers/basic_prerequisites

# run ruby unit tests
echo_divider_with_text "+-=======-" "rake test"
rake_test_output="$(rake test)" || accumulate_error "rake test FAILED"
# trim blank space and anything non-deterministic out of test output:
echo "$rake_test_output" | grep -v " --seed" | grep -v "^Finished" | grep -v "^$"
# TODO TODO: what can I do to make coverage results be trustworthy and meaningful?
# TODO TODO: perhaps ratchet coverage results towards 100%, or make sure it clears a predefined minimum threshold

exit_with_any_accumulated_errors
