#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

$THIS_DIR/install --non-interactive || exit_with_error could not install # TODO: implement --non-interactive
# TODO: run ruby unit tests

