#!/usr/bin/env bash

. $SKIGGETY_UTILS_DIR/lib/skiggety-utils.bash || exit 1

THIS_NAME="$(basename $0)"
#
# NOTE: this must be the very last thing in the script, so that the exit code passes through:
$(nextwhich $THIS_NAME) --exclude-dir coverage_links \
                        --exclude-dir coverage \
                        --exclude-dir .git \
                        --exclude-dir todo_report \
                        $*
