#!/usr/bin/env bash

THIS_DIR="$(cd "$(dirname $BASH_SOURCE)";pwd)"
. $THIS_DIR/../lib/skiggety-utils.bash || exit 1

# This script installs the latest skiggety-utils

# TODO TODO: consider making this runnable from anwhere. You'd have to pushd to the dir and move this script from PWD_BIN to bin
git pull || exit_with_error "could not pull latest changes from git"

$THIS_DIR/install-skiggety-utils "$@" || exit 1
